@startuml Diagramme de séquence
skinparam Style strictuml
title Diagramme de séquence PatronStragégieComparator

actor main
participant AgeComparator

main -> AgeComparator ** : ageComparator = new()
main -> Compagnie ** : compagnie = new(ageComparator)
main -> Compagnie : temp = toString()
main -> System.out : println(temp)

main -> SalaireComparator ** : salaireComparator = new()
main -> Compagnie : setComparatorStrategy(salaireComparator)
main -> Compagnie : temp = toString()
main -> System.out : println(temp)

@enduml