
@startuml Diagramme de classe
skinparam style strict

class Analyser
class ComplaintHandler extends Handler
class Demo 
class FanHandler extends Handler
abstract class Handler{
  	+setProchain(Handler successor) : void
	  +handleRequest(Mail mail): void
	  +printMsg(String s) : void
}
class Mail 
class NewLocationHandler extends Handler
class NormalHandler extends Handler
class SpamHandler extends Handler

Demo -> "*" Handler
Handler -up-> Mail: Analyse
Analyser -> Handler
Demo -> Analyser
Handler -down-> Handler: prochain hanbler
@enduml