@startuml
annotation org.junit.Test
class Framework.Queue.AbstractCollection
class Framework.Queue.NameComparator
class Framework.Queue.Queue
class Framework.Queue.QueueDemo
class Framework.Queue.QueueTest
class org.junit.Assert
interface Framework.Queue.Comparator
Framework.Queue.NameComparator --|> Framework.Queue.Comparator
Framework.Queue.Queue --|> Framework.Queue.AbstractCollection
Framework.Queue.QueueTest ..> org.junit.Test
Framework.Queue.QueueTest ..> org.junit.Assert
@enduml