@startuml diagamme de classe
skinparam Style strictuml
interface IStrategyRabais <<interface>>{
    +getCost() : Double 
}
class StrategiePourcentageRemise{
    -strategyRabais : IStrategyRabais
    -pourcentageRemise : Double
    +getCost() : Double
}
class StrategieRemiseAPartirDe{
    -strategyRabais : IStrategyRabais
    -rabais : Double
    -aPartirDe : Double
    +getCost() : Double
}

StrategiePourcentageRemise .up-|> IStrategyRabais
StrategieRemiseAPartirDe .up-|> IStrategyRabais

@enduml


@startuml diagamme de séquence
skinparam   Style strictuml
title Diagramme de séquence PatronStrategieRabais

actor RabaisDemo
participant ": IStartegyRabais" as IStrategyRabais
participant ": StrategiePourcentageRemise" as StrategiePourcentageRemise
participant ": StrategieRemiseAPartirDe" as StrategieRemiseAPartirDe



  


@enduml