@startuml diagamme de classe
interface IStrategyRabais{
    getCost(): Double
}

interface IStrategyRabais{
    getCost() : Double
}
class StrategiePourcentageRemise{
   strategyRabais : IStrategyRabais
   pourcentageRemise : Double
   getCost() : Double
}
class StrategieRemiseAPartirDe{
    strategyRabais : IStrategyRabais
    rabais : Double
    aPartirDe : Double
    getCost() : Double
}

IStrategyRabais <|.. StrategiePourcentageRemise
IStrategyRabais <|.. StrategieRemiseAPartirDe

@enduml


@startuml diagamme de séquence

title N/A

@enduml