@startuml
skinparam style strictuml
 interface Iterable {
	 createIterator(): Iterateur
}
 interface Iterateur {
	 hasNext(): boolean
	 next(): Object
}

class MaCollection {
  MAX: int
  compteur: int
  tableau: Object[MAX]
  ajouter(Object o): void
  createIterator(): Iterateur
}

class UneAutreCollection{
    createIterator(): Iterateur

}
class MaCollection implements Iterable 

class MonClient {
	imprimer(Iterable unIterable): void
}

class MaCollectionIterateur implements Iterateur

class UneAutreCollection implements Iterable 

 class Item {
		suivant: Item
		donnee: Object
		
		Item(Object donnee): void 
	ajouter(Object o): void
	 createIterator(): Iterateur
   }

class UneAutreCollection{}   
	
	class UneAutreCollectionIterateur {
		 courantIterateur: Item
		  hasNext(): boolean
     next(): Object
	}
class UneAutreCollectionIterateur implements Iterateur
MaCollection *-- MaCollectionIterateur
UneAutreCollection *-- UneAutreCollectionIterateur

UneAutreCollection -> Item: debut
UneAutreCollection -> Item: courant

MonClient .-right-> Iterable: dependency
MaCollection --> "*" Item
@enduml