@startuml diagamme de classe
skinparam style strict

class Frame
class FormLayout implements LayoutManager

class FormLayout {
    -left : int
    -right : int
    -height : int
    -{static} GAP : int
    +preferredLayoutSize(parent: Container): Dimension
    +minimumLayoutSize(parent: Container): Dimension
    +layoutContainer(parent: Container): Dimension
    +addLayoutComponent(parent: Container): Dimension
    +removeLayoutComponent(parent: Container): Dimension
}

Frame -> LayoutManager: use
@enduml

@startuml diagamme de séquence
skinparam Style strictuml
title Diagramme de séquence FormLayout
actor main
participant "frame:JFrame" as Frame
participant ":FormLayout" as FormLayout
participant "name:Jlabel" as name
participant "text:JTextField" as text
main --> Frame**: frame = new()
main --> FormLayout**: layout = new()
main -> Frame : frame.setLayout(layout)
main --> name**: create("Name")
main -> Frame : frame.add(name)
main --> text**: create(15)
main -> Frame : frame.add(text)
...
main -> Frame : frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
main -> Frame : frame.pack()
main -> Frame : frame.setVisible(true) 

@enduml